spring:
  cloud:
    config:
      server:
        git:
          uri: file://d:/temp/terawarehouse/git  application:    name: configuration-server
server:
  error:
    whitelabel:
      enabled: true
  port: 8000